# Generated by Django 3.1.3 on 2020-12-10 14:25

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_delete_old"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("displayname", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=10000)),
                (
                    "avatar",
                    models.FileField(
                        storage=api.models.select_storage, upload_to="artist_avatars"
                    ),
                ),
            ],
        ),
    ]
