# Generated by Django 3.1.3 on 2020-12-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_extend_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='state',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Running')], default=0),
        ),
    ]
