# Generated by Django 3.1.3 on 2020-12-20 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0006_add_concert_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="userId",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="auth.user",
            ),
            preserve_default=False,
        ),
    ]
